### ISSUE TITLE
Error when start

### ISSUE THREAD

**Issue by wiz101l** [evilsockett/shodanwave#10]
Traceback (most recent call last):
  File "./shodanwave.py", line 357, in <module>
    main()
  File "./shodanwave.py", line 342, in main
    NetworkSearchosts()
  File "./shodanwave.py", line 265, in NetworkSearchosts
    log(host, port, country, city, org, product)
  File "./shodanwave.py", line 348, in log
    file = open(filename, 'a')
IOError: [Errno 2] No such file or directory: ''

**Comment by evilsockett** [comment]
try --output hosts.txt
